# Generated by Django 4.2.3 on 2023-07-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisment', '0002_alter_advertisment_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisment',
            table='advertisment',
        ),
    ]
