# Generated by Django 4.2.3 on 2023-07-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisment', '0003_alter_advertisment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='auction_test',
            field=models.BooleanField(default=False, help_text='Возможен торг или нет', verbose_name='торг'),
        ),
    ]
