# Generated by Django 4.2.3 on 2023-07-29 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisment', '0005_remove_advertisment_date_advertisment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisment',
            table=None,
        ),
    ]
