# Generated by Django 4.2.3 on 2023-07-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisment', '0006_alter_advertisment_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisment',
            table='advertisment',
        ),
    ]
