# Generated by Django 4.2.3 on 2023-08-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisment', '0009_alter_advertisment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='image',
            field=models.ImageField(default=0, upload_to='advertisment/', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
