# Generated by Django 4.2.3 on 2023-08-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisment', '0010_advertisment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='image',
            field=models.ImageField(upload_to='advertisment/media', verbose_name='изображение'),
        ),
    ]
